In [1]:
#Description:
#   Initial and simple analysis of FBI Crime Data prior to 7/11 class
#   OFFENDER-data-controller : Endpoints pertaining to NIBRS Victim Demographic data (STATE)
#
#Modification History:
#   DD-MMM-YYY  Author          Description
#   16-07-2019  Stacey Smith    INITIAL CREATION

In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import json
import csv

from pprint import pprint

# Import DATA.GOV API key ......................REMEMBER TO PLUG IN YOUR OWN KEY NAME HERE
from api_keys import ses_dg_key

In [3]:
#Clunky but works.  There are 3 pages of data for states.  
#This pulls the data for each page and combines it all into one usable dataframe: state_data

state_qry = "https://api.usa.gov/crime/fbi/sapi/api/states?api_key=" + ses_dg_key 
state_results_1 = requests.get(state_qry, params={'page':0}).json()
state_results_2 = requests.get(state_qry, params={'page':1}).json()
state_results_3 = requests.get(state_qry, params={'page':2}).json()

sr1_df = pd.DataFrame(state_results_1['results'])
sr2_df = pd.DataFrame(state_results_2['results'])
sr3_df = pd.DataFrame(state_results_3['results'])


state_data = pd.concat([sr1_df, sr2_df, sr3_df])
state_data.head()

state_data.to_csv("output_data/state_data.csv")

In [4]:
#This is the same series created before
states = (state_data.iloc[:,1]).astype(str)

#Opened an empty list to initialize a dataframe
empty_list = []

ageDF = pd.DataFrame(empty_list)

#Creating columns on list based on the returned data for one state
ageDF["State"] = ""
ageDF["Year"] = ""
ageDF["Unknown"] = ""
ageDF["0-9"] = ""
ageDF["10-19"] = ""
ageDF["20-29"] = ""
ageDF["30-39"] = ""
ageDF["40-49"] = ""
ageDF["50-59"] = ""
ageDF["60-69"] = ""
ageDF["70-79"] = ""
ageDF["80-89"] = ""
ageDF["90-99"] = ""


#This is the loop to fill the dataframe.  This should work for any of us pulling the data from the FBI
#state APIs, with just tweaking the url, keyword and return information.

#The loop stores the return results for an individual state.  Then it loops through the return results to 
#populate each row in the empty dataframe created before.  Once it has looped through all of the return info,
#it goes back to the beginning and does the same for the next state in states.

#I found the "dataframe.append" bit on a website and it turned out to be the key to filling in the dataframe
#because it ignores index numbers and just appends to the next empty row available.  

for i in states:
    
    state = i 
    
    age_query_url = "https://api.usa.gov/crime/fbi/sapi/api/data/nibrs/homicide/offender/states/"+ state +"/age?api_key=" + ses_dg_key
    age_response_state = requests.get(age_query_url).json()
    
    for i in age_response_state['results']:
        
        ageDF = ageDF.append({'State': state, 
                          'Year': i['data_year'], 
                          'Unknown': i['unknown'],
                          '0-9' : i['range_0_9'],
                          '10-19' : i['range_10_19'],
                          '20-29' : i['range_20_29'],
                          '30-39' : i['range_30_39'],
                          '40-49' : i['range_40_49'],
                          '50-59' : i['range_50_59'],
                          '60-69' : i['range_60_69'],
                          '70-79' : i['range_70_79'],
                          '80-89' : i['range_80_89'],
                          '90-99' : i['range_90_99']},
                          ignore_index = True)
    
ageDF.to_csv("output_data/offender-ageDF.csv") 
ageDF

,State,Year,Unknown,0-9,10-19,20-29,30-39,40-49,50-59,60-69,70-79,80-89,90-99
0,AL,1991,353,0,51,82,72,30,11,5,1,2,0
1,AL,1992,102,0,46,94,52,36,13,6,4,1,0
2,AL,2006,0,0,3,2,0,0,0,0,0,0,0
3,AL,2008,0,0,2,0,1,0,0,0,0,0,0
4,AL,2009,0,0,0,1,0,2,0,0,0,0,0
5,AL,2010,0,0,0,3,0,0,0,0,0,0,0
6,AL,2012,0,0,0,1,1,0,0,0,0,0,0
7,AL,2013,0,0,0,1,0,0,1,0,0,0,0
8,AL,2014,0,0,0,1,0,0,0,0,0,0,0
9,AL,2015,0,0,0,2,1,0,0,0,0,0,0
10,AL,2016,0,0,3,1,0,0,0,0,0,0,0
11,AL,2017,0,0,2,1,0,0,0,0,0,0,0
12,AR,2001,0,0,0,2,0,0,0,0,0,0,0
13,AR,2002,0,0,0,1,0,1,0,0,0,0,0
14,AR,2003,4,0,9,15,6,7,2,2,0,0,0
15,AR,2004,9,0,7,30,15,17,5,1,0,0,0
16,AR,2005,14,0,23,37,19,13,4,3,0,0,1
17,AR,2006,15,0,13,30,24,17,3,1,0,0,0
18,AR,2007,11,0,14,31,16,20,8,3,0,1,0
19,AR,2008,11,0,16,39,20,9,9,5,2,0,0
20,AR,2009,33,0,31,89,28,18,5,6,1,0,0
21,AR,2010,25,0,24,48,29,14,6,3,0,1,0
22,AR,2011,40,0,17,64,32,20,8,3,1,0,1
23,AR,2012,43,0,33,74,46,22,10,2,0,0,0
24,AR,2013,27,0,19,72,22,23,14,2,2,1,0
25,AR,2014,30,0,15,79,37,14,14,6,1,0,0
26,AR,2015,24,0,33,88,37,22,21,2,2,0,0
27,AR,2016,36,0,32,96,41,22,19,4,2,0,0
28,AR,2017,57,0,42,90,48,32,13,3,1,0,0
29,AZ,2005,0,0,0,0,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
624,WI,2008,8,0,43,77,22,7,4,0,1,0,0
625,WI,2009,17,0,33,75,17,12,5,0,0,0,0
626,WI,2010,25,0,45,98,24,17,10,2,1,1,0
627,WI,2011,26,0,49,80,24,13,6,0,1,0,0
628,WI,2012,42,0,49,96,23,6,5,1,1,0,0
629,WI,2013,53,0,37,109,29,15,5,2,1,0,0
630,WI,2014,42,0,30,103,28,7,8,0,0,0,0
631,WI,2015,65,0,37,115,33,14,11,2,1,0,0
632,WI,2016,80,0,22,117,51,25,6,1,1,0,0
633,WI,2017,76,0,26,96,58,18,9,1,0,1,0
634,WV,1998,3,0,3,8,3,3,1,1,0,0,0
635,WV,1999,4,1,10,13,21,14,8,2,1,0,0
636,WV,2000,7,0,4,18,11,7,3,1,1,0,4
637,WV,2001,4,0,5,13,10,3,3,2,0,1,1
638,WV,2002,3,0,13,23,18,9,7,2,0,0,2
639,WV,2003,7,0,5,23,9,9,8,1,0,0,0
640,WV,2004,5,0,8,25,10,5,5,4,1,0,0
641,WV,2005,1,0,12,36,18,15,5,0,0,0,0
642,WV,2006,2,0,11,16,13,13,8,8,0,0,0
643,WV,2007,3,1,12,15,16,14,8,0,1,0,1
644,WV,2008,6,0,2,26,12,13,9,2,1,0,0
645,WV,2009,6,0,10,27,16,15,5,2,1,1,1
646,WV,2010,1,0,8,17,12,7,6,2,0,0,0
647,WV,2011,2,1,6,38,15,13,5,3,3,1,0
648,WV,2012,2,0,9,26,12,12,7,1,1,2,0
649,WV,2013,3,0,4,22,13,6,6,3,0,0,0
650,WV,2014,4,0,6,34,25,12,15,2,1,1,0
651,WV,2015,5,1,8,33,16,5,12,2,1,0,0
652,WV,2016,10,0,9,33,22,9,5,5,0,2,0
653,WV,2017,8,0,3,26,23,7,5,4,1,0,1

In [5]:
#Opened an empty list to initialize a dataframe
empty_list = []

sexDF = pd.DataFrame(empty_list)

#Creating columns on list based on the returned data for one state
sexDF["State"] = ""
sexDF["Year"] = ""
sexDF["Female Count"] = ""
sexDF["Male Count"] = ""
sexDF["Unknown"] = ""


#This is the loop to fill the dataframe.  This should work for any of us pulling the data from the FBI
#state APIs, with just tweaking the url, keyword and return information.

#The loop stores the return results for an individual state.  Then it loops through the return results to 
#populate each row in the empty dataframe created before.  Once it has looped through all of the return info,
#it goes back to the beginning and does the same for the next state in states.

#I found the "dataframe.append" bit on a website and it turned out to be the key to filling in the dataframe
#because it ignores index numbers and just appends to the next empty row available.  

for i in states:
    
    state = i 
    
    sex_query_url = "https://api.usa.gov/crime/fbi/sapi/api/data/nibrs/homicide/offender/states/"+ state +"/sex?api_key=" + ses_dg_key
    sex_response_state = requests.get(sex_query_url).json()
    
    for i in sex_response_state['results']:
        
        sexDF = sexDF.append({'State': state, 
                          'Year': i['data_year'], 
                          'Female Count': i['female_count'],
                          'Male Count' : i['male_count'],
                          'Unkown' : i['unknown']},
                          ignore_index = True)
    
    
sexDF.to_csv("output_data/offender-sexDF.csv") 
sexDF

    State  Year Female Count Male Count Unknown  Unkown
0      AL  1991           44        237     NaN   326.0
1      AL  1992           48        240     NaN    66.0
2      AL  2006            0          5     NaN     0.0
3      AL  2008            0          3     NaN     0.0
4      AL  2009            1          2     NaN     0.0
5      AL  2010            0          3     NaN     0.0
6      AL  2012            0          2     NaN     0.0
7      AL  2013            1          1     NaN     0.0
8      AL  2014            0          1     NaN     0.0
9      AL  2015            0          3     NaN     0.0
10     AL  2016            0          4     NaN     0.0
11     AL  2017            0          3     NaN     0.0
12     AR  2001            1          1     NaN     0.0
13     AR  2002            1          1     NaN     0.0
14     AR  2003            6         35     NaN     4.0
15     AR  2004            9         67     NaN     8.0
16     AR  2005           11         95     NaN     8.0
17     AR  2006           17         76     NaN    10.0
18     AR  2007           16         85     NaN     3.0
19     AR  2008            8         99     NaN     4.0
20     AR  2009           32        160     NaN    19.0
21     AR  2010           14        116     NaN    20.0
22     AR  2011           26        134     NaN    26.0
23     AR  2012           27        175     NaN    28.0
24     AR  2013           15        147     NaN    20.0
25     AR  2014           26        147     NaN    23.0
26     AR  2015           32        177     NaN    20.0
27     AR  2016           26        198     NaN    28.0
28     AR  2017           32        211     NaN    43.0
29     AZ  2005            0          2     NaN     0.0
..    ...   ...          ...        ...     ...     ...
624    WI  2008           12        145     NaN     5.0
625    WI  2009           11        135     NaN    13.0
626    WI  2010           16        197     NaN    10.0
627    WI  2011           20        169     NaN    10.0
628    WI  2012           16        183     NaN    24.0
629    WI  2013           23        203     NaN    25.0
630    WI  2014           29        177     NaN    12.0
631    WI  2015           21        215     NaN    42.0
632    WI  2016           37        208     NaN    58.0
633    WI  2017           33        206     NaN    46.0
634    WV  1998            6         15     NaN     1.0
635    WV  1999           13         57     NaN     4.0
636    WV  2000            8         44     NaN     4.0
637    WV  2001            6         32     NaN     4.0
638    WV  2002           14         60     NaN     3.0
639    WV  2003            8         52     NaN     2.0
640    WV  2004            9         51     NaN     3.0
641    WV  2005           15         72     NaN     0.0
642    WV  2006           16         53     NaN     2.0
643    WV  2007           11         58     NaN     2.0
644    WV  2008           13         55     NaN     3.0
645    WV  2009           14         67     NaN     3.0
646    WV  2010            8         45     NaN     0.0
647    WV  2011            8         77     NaN     2.0
648    WV  2012            9         59     NaN     4.0
649    WV  2013            9         46     NaN     2.0
650    WV  2014           25         67     NaN     8.0
651    WV  2015           11         71     NaN     1.0
652    WV  2016           16         74     NaN     5.0
653    WV  2017           15         59     NaN     4.0

[654 rows x 6 columns]